# Generated by Django 4.0.6 on 2023-04-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_options_order_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='archived',
        ),
    ]
